insert into genero (id, nome) values (28, "Ação");
insert into genero (id, nome) values (12, "Aventura");
insert into genero (id, nome) values (16, "Animação");
insert into genero (id, nome) values (35, "Comédia");
insert into genero (id, nome) values (80, "Crime");
insert into genero (id, nome) values (99, "Documentário");
insert into genero (id, nome) values (18, "Drama");
insert into genero (id, nome) values (10751, "Família");
insert into genero (id, nome) values (14, "Fantasia");
insert into genero (id, nome) values (36, "História");
insert into genero (id, nome) values (27, "Terror");
insert into genero (id, nome) values (10402, "Música");
insert into genero (id, nome) values (9648, "Mistério");
insert into genero (id, nome) values (10749, "Romance");
insert into genero (id, nome) values (878, "Ficção científica");
insert into genero (id, nome) values (10770, "Cinema TV");
insert into genero (id, nome) values (53, "Thriller");
insert into genero (id, nome) values (10752, "Guerra");
insert into genero (id, nome) values (37, "Faroeste");
